- name: Install pacman-contrib
  become: true
  ansible.builtin.package:
    name: pacman-contrib
    state: present

- name: Disable paccache.service
  become: true
  ansible.builtin.systemd_service:
    name: paccache.service
    enabled: false

- name: Enable paccache.timer
  become: true
  ansible.builtin.systemd_service:
    name: paccache.timer
    enabled: true
    state: started
