# Must be one of wg-quick, NetworkManager
wg_backend: wg-quick

wg_name: wg0
wg_listen_port: 51280
#wg_private_key:
#wg_addr4:
#wg_addr6:
#wg_peers:
wg_server: false

wg_autoconnect: false

wg_dependent_services: []

wg_tunnel_everything: false
