- name: Install Reflector
  become: true
  ansible.builtin.package:
    name: reflector
    state: present

- name: Disable reflector.service
  become: true
  ansible.builtin.systemd_service:
    name: reflector.service
    enabled: false

- name: Enable reflector.timer
  become: true
  ansible.builtin.systemd_service:
    name: reflector.timer
    enabled: true
    state: started
